version: '3.8'

services:
    micro-stack:
        image: micro-stack:latest
        container_name: micro-stack
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 4321:4321
