version: '3.8'

services:
    micro-stack:
        container_name: micro-stack
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 4321:4321
