name = "micro-stack"
compatibility_date = "2024-01-17"
main = "dist/_worker.js"

[[d1_databases]]
binding = "DATABASE"
database_id = "d0309751-05a7-420f-adcf-dc81f416670d" # Random UUID for local development only.
migrations_table = "__drizzle_migrations"
migrations_dir = "./src/database/migrations/"

[placement]
mode = "smart"
